# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07a3d462be8eeb09849c2c5f96f8c159785815406bf22af4978992ecb51e4635f4bfa755b81e21a0e9e1086872a3d1e8503bd4c496f2c925e7987b93eb1aa2a5

test:
  secret_key_base: 30893541aad73a2bfd4b4bbcad4676f4254b32dec04477f0fce166f9e80fb4e0e7d4a2d7d68cc7212e712496561140e60812321894cdc85c10a1db1a7193a5a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
